-- Phase 1 SQLite contract. A Drift implementation can adopt this without changing domain APIs.
CREATE TABLE categories (local_id TEXT PRIMARY KEY, server_id TEXT, name TEXT NOT NULL, active INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, sync_status TEXT NOT NULL);
CREATE TABLE products (local_id TEXT PRIMARY KEY, server_id TEXT, category_id TEXT NOT NULL, name TEXT NOT NULL, sku TEXT NOT NULL, barcode TEXT, purchase_price INTEGER NOT NULL, selling_price INTEGER NOT NULL, tax_percent REAL NOT NULL, stock INTEGER NOT NULL, minimum_stock INTEGER NOT NULL, unit TEXT NOT NULL, active INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, sync_status TEXT NOT NULL);
CREATE TABLE customers (local_id TEXT PRIMARY KEY, server_id TEXT, name TEXT NOT NULL, phone TEXT, email TEXT, address TEXT, tax_number TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, sync_status TEXT NOT NULL);
CREATE TABLE sales (local_id TEXT PRIMARY KEY, server_id TEXT, invoice_no TEXT NOT NULL, customer_id TEXT, subtotal INTEGER NOT NULL, discount INTEGER NOT NULL, tax INTEGER NOT NULL, total INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, sync_status TEXT NOT NULL);
CREATE TABLE sale_items (local_id TEXT PRIMARY KEY, sale_id TEXT NOT NULL, product_id TEXT NOT NULL, quantity INTEGER NOT NULL, unit_price INTEGER NOT NULL, discount INTEGER NOT NULL, tax INTEGER NOT NULL, total INTEGER NOT NULL);
CREATE TABLE purchase_bills (local_id TEXT PRIMARY KEY, server_id TEXT, supplier_id TEXT, invoice_no TEXT NOT NULL, total INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, sync_status TEXT NOT NULL);
CREATE TABLE purchase_items (local_id TEXT PRIMARY KEY, purchase_id TEXT NOT NULL, product_id TEXT NOT NULL, quantity INTEGER NOT NULL, rate INTEGER NOT NULL, tax INTEGER NOT NULL, discount INTEGER NOT NULL, total INTEGER NOT NULL);
CREATE TABLE inventory_transactions (local_id TEXT PRIMARY KEY, server_id TEXT, product_id TEXT NOT NULL, quantity_delta INTEGER NOT NULL, reason TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, sync_status TEXT NOT NULL);
CREATE TABLE payments (local_id TEXT PRIMARY KEY, server_id TEXT, sale_id TEXT NOT NULL, method TEXT NOT NULL, amount INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, sync_status TEXT NOT NULL);
CREATE TABLE sync_queue (local_id TEXT PRIMARY KEY, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, payload TEXT, attempts INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, sync_status TEXT NOT NULL);
CREATE TABLE app_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL);
