import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

final localeProvider = NotifierProvider<LocaleController, Locale>(
  LocaleController.new,
);

class LocaleController extends Notifier<Locale> {
  static const _key = 'app_locale';

  @override
  Locale build() {
    _restore();
    return const Locale('en');
  }

  Future<void> _restore() async {
    final saved = (await SharedPreferences.getInstance()).getString(_key);
    if (saved != null && saved != state.languageCode) {
      state = Locale(saved);
    }
  }

  Future<void> setLanguage(String code) async {
    state = Locale(code);
    await (await SharedPreferences.getInstance()).setString(_key, code);
  }
}

class AppLocalizations {
  const AppLocalizations(this.locale);
  final Locale locale;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const delegate = _AppLocalizationsDelegate();

  String tr(String text) =>
      locale.languageCode == 'ar' ? _ar[text] ?? text : text;
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      const ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension LocalizationBuildContext on BuildContext {
  String tr(String text) => AppLocalizations.of(this).tr(text);
  bool get isArabic => Localizations.localeOf(this).languageCode == 'ar';
}

const Map<String, String> _ar = {
  'Active': 'نشط',
  'Add Product': 'إضافة منتج',
  'Add cash': 'إضافة نقدية',
  'Add opening stock': 'إضافة مخزون افتتاحي',
  'Add subcategory': 'إضافة فئة فرعية',
  'Add supplier': 'إضافة مورد',
  'All categories': 'كل الفئات',
  'All locations': 'كل المواقع',
  'All statuses': 'كل الحالات',
  'Apply filters': 'تطبيق عوامل التصفية',
  'B2B · Business': 'أعمال · شركة',
  'B2C · Retail': 'أفراد · تجزئة',
  'Barcode printer': 'طابعة الباركود',
  'Billing printer': 'طابعة الفواتير',
  'Browse products': 'تصفح المنتجات',
  'Business (B2B)': 'شركة (أعمال)',
  'Cancelled': 'ملغي',
  'Clear defaults': 'مسح الإعدادات الافتراضية',
  'Clear filters': 'مسح عوامل التصفية',
  'Completed': 'مكتمل',
  'Continue': 'متابعة',
  'Create Order': 'إنشاء طلب',
  'Current': 'الحالي',
  'Date': 'التاريخ',
  'Days': 'أيام',
  'Delete': 'حذف',
  'Done': 'تم',
  'Download': 'تنزيل',
  'Draft': 'مسودة',
  'Edit': 'تعديل',
  'Export PDF': 'تصدير PDF',
  'Failed': 'فشل',
  'Filters': 'عوامل التصفية',
  'Fixed amount': 'مبلغ ثابت',
  'Inactive': 'غير نشط',
  'Items': 'الأصناف',
  'Kitchen printer': 'طابعة المطبخ',
  'Last 30 days': 'آخر 30 يوماً',
  'Last 7 days': 'آخر 7 أيام',
  'Loading ZATCA invoice status…': 'جارٍ تحميل حالة فاتورة زاتكا…',
  'Name (A to Z)': 'الاسم (أ إلى ي)',
  'New category': 'فئة جديدة',
  'No products are available.': 'لا توجد منتجات متاحة.',
  'None': 'لا شيء',
  'Not synced': 'غير متزامن',
  'Only active products': 'المنتجات النشطة فقط',
  'Open cash register': 'فتح صندوق النقد',
  'Ordered': 'تم الطلب',
  'Overview': 'نظرة عامة',
  'POS sale': 'بيع نقطة البيع',
  'Partially received': 'مستلم جزئياً',
  'Percentage': 'نسبة مئوية',
  'Preview': 'معاينة',
  'Price': 'السعر',
  'Purchase cost': 'تكلفة الشراء',
  'Qty': 'الكمية',
  'Quotation printer': 'طابعة عروض الأسعار',
  'Received': 'مستلم',
  'Reload config': 'إعادة تحميل الإعدادات',
  'Remove cash': 'سحب نقدية',
  'Reset': 'إعادة تعيين',
  'Retry': 'إعادة المحاولة',
  'Returned': 'مرتجع',
  'SKU': 'رمز المنتج',
  'Save settings': 'حفظ الإعدادات',
  'Save supplier': 'حفظ المورد',
  'Scan for printers': 'البحث عن الطابعات',
  'Status': 'الحالة',
  'Supplier': 'المورد',
  'Test print': 'طباعة تجريبية',
  'Total amount': 'المبلغ الإجمالي',
  'Try again': 'حاول مرة أخرى',
  'Unit Cost': 'تكلفة الوحدة',
  'Unit Price': 'سعر الوحدة',
  'Update': 'تحديث',
  'View': 'عرض',
  'View details': 'عرض التفاصيل',
  'XML': 'XML',
  'ZATCA': 'زاتكا',
  'ADD ANOTHER USER': 'إضافة مستخدم آخر',
  'Add a new supplier to your business': 'إضافة مورد جديد إلى نشاطك التجاري',
  'Add a reusable UOM for products and inventory.':
      'أضف وحدة قياس قابلة لإعادة الاستخدام للمنتجات والمخزون.',
  'Add and switch': 'إضافة وتبديل',
  'Add at least one valid product line.':
      'أضف صنف منتج صالحاً واحداً على الأقل.',
  'Allow decimal quantities': 'السماح بالكميات العشرية',
  'Allow overselling': 'السماح بالبيع فوق المخزون',
  'Assign a customer to the current order.': 'عيّن عميلاً للطلب الحالي.',
  'Barcode sticker layout': 'تنسيق ملصق الباركود',
  'Both standard & simplified': 'قياسية ومبسطة',
  'Browse Products': 'تصفح المنتجات',
  'Business location sync windows': 'فترات مزامنة مواقع النشاط',
  'CURRENT PACKAGE': 'الباقة الحالية',
  'Cash movements': 'الحركات النقدية',
  'Cash register': 'صندوق النقد',
  'Category deleted.': 'تم حذف الفئة.',
  'Category saved.': 'تم حفظ الفئة.',
  'Change order status': 'تغيير حالة الطلب',
  'Change status': 'تغيير الحالة',
  'Check your connection and try again.': 'تحقق من اتصالك وحاول مرة أخرى.',
  'Clear selection': 'مسح التحديد',
  'Close and reconcile': 'إغلاق وتسوية',
  'Close and reconcile register': 'إغلاق الصندوق وتسويته',
  'Close register': 'إغلاق الصندوق',
  'Compliance information': 'معلومات الامتثال',
  'Configure automatic reporting and review synchronization health.':
      'إعداد الإبلاغ التلقائي ومراجعة حالة المزامنة.',
  'Contact type': 'نوع جهة الاتصال',
  'Create and manage a new supplier order': 'إنشاء وإدارة طلب مورد جديد',
  'Create unit of measure': 'إنشاء وحدة قياس',
  'Customer: Walk-in Customer': 'العميل: عميل نقدي',
  'Daily — B2C reporting queue': 'يومي — قائمة إبلاغ فواتير الأفراد',
  'Default printer for this app': 'الطابعة الافتراضية لهذا التطبيق',
  'Delete / replace': 'حذف / استبدال',
  'Delete or replace category': 'حذف الفئة أو استبدالها',
  'Delete product': 'حذف المنتج',
  'Delete product?': 'حذف المنتج؟',
  'Developer portal': 'بوابة المطور',
  'Direct sale': 'بيع مباشر',
  'Disable invoice discounts': 'تعطيل خصومات الفاتورة',
  'Disable order-level tax': 'تعطيل الضريبة على مستوى الطلب',
  'Environment & authorization': 'البيئة والصلاحيات',
  'Filter purchases': 'تصفية المشتريات',
  'Individual (B2C)': 'فرد (B2C)',
  'Instant — required for B2B clearance': 'فوري — مطلوب لاعتماد فواتير الشركات',
  'Invoice customer type': 'نوع عميل الفاتورة',
  'Invoice documents': 'مستندات الفاتورة',
  'Loading ZATCA status': 'جارٍ تحميل حالة زاتكا',
  'Manage compliance, EGS devices and invoice submissions.':
      'إدارة الامتثال وأجهزة EGS وإرسال الفواتير.',
  'Manage subcategories': 'إدارة الفئات الفرعية',
  'Manual only': 'يدوي فقط',
  'Mark completed': 'تحديد كمكتمل',
  'Months': 'أشهر',
  'More information': 'معلومات إضافية',
  'No products added yet': 'لم تتم إضافة منتجات بعد',
  'No summary available.': 'لا يوجد ملخص متاح.',
  'Notes': 'ملاحظات',
  'Official invoice layout': 'تنسيق الفاتورة الرسمي',
  'Offline POS is ready on this device.':
      'نقطة البيع دون اتصال جاهزة على هذا الجهاز.',
  'Offline POS readiness': 'جاهزية نقطة البيع دون اتصال',
  'Offline catalog is up to date.': 'كتالوج وضع عدم الاتصال محدّث.',
  'Onboard ZATCA device': 'تهيئة جهاز زاتكا',
  'Open preview again': 'فتح المعاينة مجدداً',
  'Open, manage and reconcile the cashier drawer.':
      'فتح درج النقد وإدارته وتسويته.',
  'Optional identifiers, terms and delivery details':
      'المعرّفات والشروط وتفاصيل التسليم الاختيارية',
  'Organization': 'المنشأة',
  'Pay term unit': 'وحدة مدة السداد',
  'Payment / sync': 'الدفع / المزامنة',
  'Payment terms': 'شروط السداد',
  'Prepare offline mode': 'تجهيز وضع عدم الاتصال',
  'Preview only • Nothing will print': 'معاينة فقط • لن تتم الطباعة',
  'Preview test document': 'معاينة مستند الاختبار',
  'Pricing': 'التسعير',
  'Print behavior': 'سلوك الطباعة',
  'Printer configuration test': 'اختبار إعداد الطابعة',
  'Product preview': 'معاينة المنتج',
  'Product setup': 'إعداد المنتج',
  'Purchase Order': 'أمر شراء',
  'Purchases  /  Purchase Orders': 'المشتريات / أوامر الشراء',
  'Quick Actions': 'إجراءات سريعة',
  'Refund total': 'إجمالي الاسترداد',
  'Registered address': 'العنوان المسجل',
  'Remove existing image': 'إزالة الصورة الحالية',
  'Retry preview': 'إعادة محاولة المعاينة',
  'Rows per page': 'صفوف الصفحة',
  'SIGNED-IN USERS': 'المستخدمون المسجلون',
  'Sale returns': 'مرتجعات المبيعات',
  'Sales invoices': 'فواتير المبيعات',
  'Save & add another': 'حفظ وإضافة آخر',
  'Save as Draft': 'حفظ كمسودة',
  'Search your inventory above to add products.':
      'ابحث في المخزون أعلاه لإضافة المنتجات.',
  'Select a business location first.': 'اختر موقع النشاط أولاً.',
  'Select a saved cashier or add another account.':
      'اختر أمين صندوق محفوظاً أو أضف حساباً آخر.',
  'Select products and at least one change.':
      'حدد المنتجات وتغييراً واحداً على الأقل.',
  'Select the items and quantities being returned.':
      'حدد الأصناف والكميات المطلوب إرجاعها.',
  'Set as default': 'تعيين كافتراضي',
  'Shipping costs & expenses': 'تكاليف ومصروفات الشحن',
  'Show results': 'عرض النتائج',
  'Simplified only': 'مبسطة فقط',
  'Sort by': 'ترتيب حسب',
  'Standard only': 'قياسية فقط',
  'Store name': 'اسم المتجر',
  'Submission policy': 'سياسة الإرسال',
  'Submission status': 'حالة الإرسال',
  'Submit / retry': 'إرسال / إعادة المحاولة',
  'Successful': 'ناجح',
  'Switch cashier?': 'تبديل أمين الصندوق؟',
  'Switch user': 'تبديل المستخدم',
  'The new UOM will be available across product creation, purchasing and inventory.':
      'ستتوفر وحدة القياس الجديدة في إنشاء المنتجات والمشتريات والمخزون.',
  'The official invoice number and ZATCA status are issued after synchronization.':
      'يتم إصدار رقم الفاتورة الرسمي وحالة زاتكا بعد المزامنة.',
  'Unable to load ZATCA integration': 'تعذر تحميل تكامل زاتكا',
  'Unable to load preview': 'تعذر تحميل المعاينة',
  'Unable to load purchases': 'تعذر تحميل المشتريات',
  'Unable to load report': 'تعذر تحميل التقرير',
  'Unable to load subscription': 'تعذر تحميل الاشتراك',
  'Update offline catalog': 'تحديث كتالوج عدم الاتصال',
  'Used automatically for sales, purchases, ZATCA and all other print actions':
      'تُستخدم تلقائياً للمبيعات والمشتريات وزاتكا وجميع عمليات الطباعة الأخرى',
  'ZATCA credit note submission': 'إرسال إشعار دائن إلى زاتكا',
  'ZATCA e-invoice details': 'تفاصيل الفاتورة الإلكترونية لزاتكا',
  'ZATCA e-invoicing': 'الفوترة الإلكترونية لزاتكا',
  'ZATCA settings': 'إعدادات زاتكا',
  'Reload ERP layouts': 'إعادة تحميل تنسيقات ERP',
  'Business location': 'موقع النشاط',
  'Document type': 'نوع المستند',
  'Close preview': 'إغلاق المعاينة',
  'Paper / label size': 'حجم الورق / الملصق',
  'Default print template': 'قالب الطباعة الافتراضي',
  'Used automatically for this document type':
      'يُستخدم تلقائياً لهذا النوع من المستندات',
  'Leave blank to auto-generate': 'اتركه فارغاً للإنشاء تلقائياً',
  'Check SKU availability': 'التحقق من توفر رمز المنتج',
  'Margin (%) — optional': 'هامش الربح (%) — اختياري',
  'Leave empty to enter the selling price directly':
      'اتركه فارغاً لإدخال سعر البيع مباشرة',
  'Unit name *': 'اسم الوحدة *',
  'e.g. Kilogram, Box, Litre': 'مثال: كيلوجرام، صندوق، لتر',
  'Symbol / short name *': 'الرمز / الاسم المختصر *',
  'e.g. kg, box, L': 'مثال: كجم، صندوق، لتر',
  'New selling price': 'سعر البيع الجديد',
  'Price: Low to high': 'السعر: من الأقل إلى الأعلى',
  'Price: High to low': 'السعر: من الأعلى إلى الأقل',
  'Stock: Low to high': 'المخزون: من الأقل إلى الأعلى',
  'Product deleted.': 'تم حذف المنتج.',
  'Fields marked required are used to produce a standard B2B tax invoice.':
      'تُستخدم الحقول المطلوبة لإصدار فاتورة ضريبية قياسية للشركات.',
  'GreenMart - Sales History': 'جرين مارت - سجل المبيعات',
  'API-backed mode': 'وضع الاتصال بواجهة API',
  'Products, categories, customers, sales, stock, and reports are loaded from EazyERP.':
      'يتم تحميل المنتجات والفئات والعملاء والمبيعات والمخزون والتقارير من EazyERP.',
  'REFERENCE': 'المرجع',
  'SUPPLIER': 'المورد',
  'ORDER DATE': 'تاريخ الطلب',
  'EXPECTED / RECEIVED': 'المتوقع / المستلم',
  'STATUS': 'الحالة',
  'ITEMS': 'الأصناف',
  'TOTAL': 'الإجمالي',
  'ACTIONS': 'الإجراءات',
  'This will be used as the default payment term when creating purchase orders.':
      'سيُستخدم هذا كشرط السداد الافتراضي عند إنشاء أوامر الشراء.',
  'Direct download is currently available on Flutter Web.':
      'التنزيل المباشر متاح حالياً على Flutter Web.',
  'ⓘ  Estimated profit per unit: ': 'ⓘ  الربح التقديري لكل وحدة: ',
  'Product image removed.': 'تمت إزالة صورة المنتج.',
  'This SKU is already in use.': 'رمز المنتج هذا مستخدم بالفعل.',
  'Product saved. Add the next product.': 'تم حفظ المنتج. أضف المنتج التالي.',
  'Unable to create the unit. Try again.': 'تعذر إنشاء الوحدة. حاول مرة أخرى.',
  'XLS, XLSX, CSV or TXT • maximum 100 MB':
      'XLS أو XLSX أو CSV أو TXT • الحد الأقصى 100 ميجابايت',
  'Sharing adapter is ready for Phase 2.':
      'مكوّن المشاركة جاهز للمرحلة الثانية.',
  'Password recovery will be connected with the backend.':
      'سيتم ربط استعادة كلمة المرور بالخادم.',
  'EGS devices / business locations': 'أجهزة EGS / مواقع النشاط',
  'Checking the integration and permitted business locations. This should only take a few seconds.':
      'جارٍ التحقق من التكامل ومواقع النشاط المسموح بها. لن يستغرق ذلك سوى بضع ثوانٍ.',
  'QR payload': 'بيانات رمز QR',
  'Print PDF/A-3': 'طباعة PDF/A-3',
  'ZATCA settings saved.': 'تم حفظ إعدادات زاتكا.',
  'Prevent discounts on ZATCA invoices.': 'منع الخصومات على فواتير زاتكا.',
  'Use line-level tax calculation only.':
      'استخدام حساب الضريبة على مستوى الصنف فقط.',
  'Simulation': 'محاكاة',
  'Production / Core': 'الإنتاج / النظام الأساسي',
  'This sale has no server transaction ID.':
      'لا تحتوي عملية البيع على معرّف معاملة من الخادم.',
  'This return has no server transaction ID.':
      'لا يحتوي المرتجع على معرّف معاملة من الخادم.',
  'ZATCA QR payload': 'بيانات رمز QR لزاتكا',
  'Package user allowances': 'حدود مستخدمي الباقة',
  'active login users': 'مستخدمون نشطون مسجلون',
  'Managed in EazyERP. This layout and its paper format are used for synchronized sales and reprints at this location.':
      'تتم إدارته في EazyERP. يُستخدم هذا التنسيق وحجم ورقه للمبيعات المتزامنة وإعادة الطباعة في هذا الموقع.',
  'Generating EazyERP preview…': 'جارٍ إنشاء معاينة EazyERP…',
  'Loading the selected layout, labels and invoice fields.':
      'جارٍ تحميل التنسيق والتسميات وحقول الفاتورة المحددة.',
  'Print date': 'تاريخ الطباعة',
  'Keyboard: ↑ ↓ select item or Pay  •  type quantity + Enter  •  Enter activates':
      'لوحة المفاتيح: ↑ ↓ لتحديد الصنف أو الدفع • اكتب الكمية ثم Enter • Enter للتنفيذ',
  'Count the actual drawer and payment slips. Variances will be recorded in the register summary.':
      'احسب النقد الفعلي وإيصالات الدفع. سيتم تسجيل الفروقات في ملخص الصندوق.',
  'Notifications': 'الإشعارات',
  'Search name, SKU or barcode': 'ابحث بالاسم أو رمز المنتج أو الباركود',
  'Category': 'الفئة',
  'Min': 'الحد الأدنى',
  'Max': 'الحد الأقصى',
  'Previous page': 'الصفحة السابقة',
  'Next page': 'الصفحة التالية',
  'English name *': 'الاسم بالإنجليزية *',
  'Arabic name (optional)': 'الاسم بالعربية (اختياري)',
  'Replacement (if required)': 'البديل (عند الحاجة)',
  'Payment term unit': 'وحدة مدة السداد',
  'Min amount': 'الحد الأدنى للمبلغ',
  'Max amount': 'الحد الأقصى للمبلغ',
  'Submit return to ZATCA': 'إرسال المرتجع إلى زاتكا',
  'Search reference, supplier or status': 'ابحث بالمرجع أو المورد أو الحالة',
  'Refresh purchases': 'تحديث المشتريات',
  'Purchase actions': 'إجراءات الشراء',
  'Supplier *': 'المورد *',
  'Business location *': 'موقع النشاط *',
  'Reference number': 'الرقم المرجعي',
  'Auto-generated if empty': 'يُنشأ تلقائياً إذا كان فارغاً',
  'Date *': 'التاريخ *',
  'Status *': 'الحالة *',
  'Shipping status': 'حالة الشحن',
  'Exchange rate': 'سعر الصرف',
  'Pay term': 'مدة السداد',
  'Expected delivery': 'التسليم المتوقع',
  'Search and add product by name or SKU': 'ابحث وأضف منتجاً بالاسم أو الرمز',
  'Discount type': 'نوع الخصم',
  'Purchase tax': 'ضريبة الشراء',
  'Shipping details': 'تفاصيل الشحن',
  'Additional shipping charges': 'رسوم الشحن الإضافية',
  'Payment method': 'طريقة الدفع',
  'Payment account': 'حساب الدفع',
  'Payment note': 'ملاحظة الدفع',
  'Back to purchases': 'العودة إلى المشتريات',
  'Order status *': 'حالة الطلب *',
  'Search products by name, SKU or barcode':
      'ابحث عن المنتجات بالاسم أو الرمز أو الباركود',
  'Shipping charges': 'رسوم الشحن',
  'Order date *': 'تاريخ الطلب *',
  'Unit cost': 'تكلفة الوحدة',
  'Discount %': 'نسبة الخصم',
  'Remove saved user': 'إزالة المستخدم المحفوظ',
  'Refresh status': 'تحديث الحالة',
  'Search invoice, customer or mobile': 'ابحث بالفاتورة أو العميل أو الجوال',
  'ZATCA status': 'حالة زاتكا',
  'Refresh': 'تحديث',
  'Open ZATCA record': 'فتح سجل زاتكا',
  'Auto sync frequency': 'تكرار المزامنة التلقائية',
  'Portal environment *': 'بيئة البوابة *',
  'Fatoora OTP *': 'رمز فاتورة لمرة واحدة *',
  'Used once and never stored': 'يُستخدم مرة واحدة ولا يتم حفظه',
  'Device contact email *': 'بريد التواصل للجهاز *',
  'Saudi VAT number *': 'الرقم الضريبي السعودي *',
  'Invoice type *': 'نوع الفاتورة *',
  'Location': 'الموقع',
  'Opening cash': 'النقد الافتتاحي',
  'Cash physically available in the drawer.': 'النقد الموجود فعلياً في الدرج.',
  'Actual cash *': 'النقد الفعلي *',
  'Actual card total': 'إجمالي البطاقات الفعلي',
  'Actual cheque total': 'إجمالي الشيكات الفعلي',
  'Closing note': 'ملاحظة الإغلاق',
  'Add supplier instructions, delivery notes, or internal comments...':
      'أضف تعليمات المورد أو ملاحظات التسليم أو التعليقات الداخلية...',
  'Add product details, specifications or internal notes...':
      'أضف تفاصيل المنتج أو المواصفات أو الملاحظات الداخلية...',
  'Back': 'رجوع',
  'Recent Sales': 'المبيعات الأخيرة',
  'Review completed transactions without leaving the POS.':
      'راجع العمليات المكتملة دون مغادرة نقطة البيع.',
  'Search invoice, customer, phone or payment method':
      'ابحث بالفاتورة أو العميل أو الهاتف أو طريقة الدفع',
  'Clear search': 'مسح البحث',
  'No completed sales are available yet': 'لا توجد مبيعات مكتملة بعد',
  'No sales match this search': 'لا توجد مبيعات تطابق البحث',
  'Invoice': 'الفاتورة',
  'Date & time': 'التاريخ والوقت',
  'Actions': 'الإجراءات',
  'Sale actions': 'إجراءات البيع',
  'Return': 'مرتجع',
  'Return (available after sync)': 'المرتجع (متاح بعد المزامنة)',
  'Unknown': 'غير معروف',
  'Remove item': 'إزالة الصنف',
  'Remove item?': 'إزالة الصنف؟',
  'Remove': 'إزالة',
  'Use ↑ / ↓ to choose an action, then press Enter.':
      'استخدم ↑ / ↓ لاختيار إجراء، ثم اضغط Enter.',
  'No payment methods available.': 'لا توجد طرق دفع متاحة.',
  'Press Enter again to confirm': 'اضغط Enter مرة أخرى للتأكيد',
  'Select payment method': 'اختر طريقة الدفع',
  'Preparing invoice and sending it to the printer…':
      'جارٍ تجهيز الفاتورة وإرسالها إلى الطابعة…',
  'Sending to printer…': 'جارٍ الإرسال إلى الطابعة…',
  'Print failed': 'فشلت الطباعة',
  'Add an item before editing its price.': 'أضف صنفاً قبل تعديل سعره.',
  'Add an item before adding a discount.': 'أضف صنفاً قبل إضافة الخصم.',
  'Scanner input is ready through the search field.':
      'إدخال الماسح جاهز عبر حقل البحث.',
  'Favorite': 'المفضلة',
  'Product actions': 'إجراءات المنتج',
  'Cash drawer command is ready.': 'أمر درج النقد جاهز.',
  'More cashier actions': 'المزيد من إجراءات أمين الصندوق',
  'Sale return created successfully.': 'تم إنشاء مرتجع البيع بنجاح.',
  'Sale held.': 'تم تعليق البيع.',
  'Resume': 'استئناف',
  'ZATCA invoice status & documents': 'حالة ومستندات فاتورة هيئة الزكاة',
  'Eazy POS': 'إيزي بوس',
  'GreenMart': 'جرين مارت',
  'Point of Sale': 'نقطة البيع',
  'POS': 'نقطة البيع',
  'Dashboard': 'لوحة التحكم',
  'Products': 'المنتجات',
  'Categories': 'الفئات',
  'Purchases': 'المشتريات',
  'Inventory': 'المخزون',
  'Customers': 'العملاء',
  'Sales': 'المبيعات',
  'Reports': 'التقارير',
  'Sync': 'المزامنة',
  'Settings': 'الإعدادات',
  'Add customer': 'إضافة عميل',
  'Edit customer': 'تعديل العميل',
  'Customer name': 'اسم العميل',
  'Mobile': 'رقم الجوال',
  'Email': 'البريد الإلكتروني',
  'Required': 'مطلوب',
  'Save': 'حفظ',
  'Search customers': 'البحث عن العملاء',
  'Good morning': 'صباح الخير',
  'Backend data': 'بيانات الخادم',
  'Line discount': 'خصم الصنف',
  'Add discount': 'إضافة خصم',
  'Discount amount': 'قيمة الخصم',
  'Maximum': 'الحد الأقصى',
  'Enter a valid amount': 'أدخل مبلغًا صحيحًا',
  'Discount cannot exceed subtotal': 'لا يمكن أن يتجاوز الخصم المجموع الفرعي',
  'Remove discount': 'إزالة الخصم',
  'Apply': 'تطبيق',
  'More': 'المزيد',
  'Online': 'متصل',
  'Synced': 'تمت المزامنة',
  'New sale': 'عملية بيع جديدة',
  'WORKSPACE': 'مساحة العمل',
  'Main Store': 'المتجر الرئيسي',
  'Administrator': 'مدير النظام',
  'Search by name, SKU or barcode...':
      'ابحث بالاسم أو رمز المنتج أو الباركود...',
  'Scan barcode or search product to add':
      'امسح الباركود أو ابحث عن منتج لإضافته',
  'All': 'الكل',
  'Grocery': 'بقالة',
  'Beverages': 'مشروبات',
  'Snacks': 'وجبات خفيفة',
  'Household': 'منزلية',
  'Personal Care': 'العناية الشخصية',
  'Grid': 'شبكة',
  'List': 'قائمة',
  'Top selling': 'الأكثر مبيعاً',
  'Current Order': 'الطلب الحالي',
  'Clear': 'مسح',
  'Walk-in Customer': 'عميل نقدي',
  'Customer': 'العميل',
  'Payment': 'الدفع',
  'Subtotal': 'المجموع الفرعي',
  'Tax (5%)': 'الضريبة (5%)',
  'Discount': 'الخصم',
  'Grand Total': 'الإجمالي',
  'View cart': 'عرض السلة',
  'Select customer': 'اختر العميل',
  'Cash': 'نقداً',
  'Card': 'بطاقة',
  'Credit sale': 'بيع آجل',
  'Payment due': 'الدفع مستحق',
  'Paid': 'مدفوع',
  'Paid sale': 'بيع مدفوع',
  'Outstanding': 'المبلغ المستحق',
  'Pay later • Customer required': 'الدفع لاحقاً • يجب تحديد العميل',
  'Select a customer first': 'اختر عميلاً أولاً',
  'Credit cannot be assigned to the Walk-in Customer. Select the customer who will pay this invoice later.':
      'لا يمكن تسجيل البيع الآجل على العميل النقدي. اختر العميل الذي سيدفع هذه الفاتورة لاحقاً.',
  'Confirm credit sale': 'تأكيد البيع الآجل',
  'No payment will be collected now. The full invoice amount will be recorded as due.':
      'لن يتم تحصيل أي مبلغ الآن. سيتم تسجيل كامل مبلغ الفاتورة كمبلغ مستحق.',
  'Credit amount': 'المبلغ الآجل',
  'Payment term': 'مدة السداد',
  'Due date': 'تاريخ الاستحقاق',
  'Not specified': 'غير محدد',
  'days': 'أيام',
  'months': 'أشهر',
  'Create credit sale': 'إنشاء بيع آجل',
  'UPI': 'دفع إلكتروني',
  'items': 'عناصر',
  'item': 'عنصر',
  'each': 'للوحدة',
  'Search products': 'البحث في المنتجات',
  'Add product': 'إضافة منتج',
  'Product name': 'اسم المنتج',
  'Selling price': 'سعر البيع',
  'Opening stock': 'المخزون الافتتاحي',
  'Cancel': 'إلغاء',
  'Save product': 'حفظ المنتج',
  'Import': 'استيراد',
  'Bulk update': 'تحديث جماعي',
  'Quick add': 'إضافة سريعة',
  'New product': 'منتج جديد',
  'Quick add product': 'إضافة منتج سريعة',
  'Edit product': 'تعديل المنتج',
  'Create product': 'إنشاء منتج',
  'Create a sellable product with optional opening stock.':
      'أنشئ منتجاً قابلاً للبيع مع مخزون افتتاحي اختياري.',
  'Product details are saved directly to EazyERP.':
      'تُحفظ تفاصيل المنتج مباشرة في إيزي ERP.',
  'Manage inventory': 'إدارة المخزون',
  'Save changes': 'حفظ التغييرات',
  'Bulk update products': 'تحديث المنتجات جماعياً',
  'Apply category, location, or selling price to selected products.':
      'طبّق الفئة أو الموقع أو سعر البيع على المنتجات المحددة.',
  'Import products': 'استيراد المنتجات',
  'Upload the EazyERP product spreadsheet template.':
      'ارفع قالب جدول منتجات إيزي ERP.',
  'Product identity': 'بيانات المنتج',
  'SKU (leave blank to auto-generate)':
      'رمز المنتج (اتركه فارغاً للإنشاء تلقائياً)',
  'Barcode type': 'نوع الباركود',
  'Brand': 'العلامة التجارية',
  'Sub category': 'الفئة الفرعية',
  'Inventory and description': 'المخزون والوصف',
  'Alert quantity': 'كمية التنبيه',
  'Enable IMEI or serial number': 'تفعيل IMEI أو الرقم التسلسلي',
  'Not for selling': 'غير مخصص للبيع',
  'Weight': 'الوزن',
  'Preparation time (minutes)': 'وقت التحضير (بالدقائق)',
  'Product description': 'وصف المنتج',
  'Business locations': 'مواقع النشاط',
  'Select every location where this product can be sold.':
      'حدد كل موقع يمكن بيع هذا المنتج فيه.',
  'Media': 'الوسائط',
  'Choose product image': 'اختر صورة المنتج',
  'Replace product image': 'استبدل صورة المنتج',
  'Choose product brochure': 'اختر كتيب المنتج',
  'Tax and product type': 'الضريبة ونوع المنتج',
  'Applicable tax': 'الضريبة المطبقة',
  'Selling price tax type': 'نوع ضريبة سعر البيع',
  'Product type': 'نوع المنتج',
  'Opening quantity': 'الكمية الافتتاحية',
  'Save & add opening stock': 'حفظ وإضافة مخزون افتتاحي',
  'Save and add another': 'حفظ وإضافة منتج آخر',
  'Default purchase price': 'سعر الشراء الافتراضي',
  'Default selling price': 'سعر البيع الافتراضي',
  'Margin (%)': 'هامش الربح (%)',
  'Excluding tax': 'غير شامل الضريبة',
  'Including tax': 'شامل الضريبة',
  'Margin': 'هامش الربح',
  'Add purchase': 'إضافة مشتريات',
  'Receive purchase': 'استلام مشتريات',
  'Product': 'المنتج',
  'Quantity': 'الكمية',
  'Purchase rate': 'سعر الشراء',
  'Save draft': 'حفظ كمسودة',
  'Save purchase': 'حفظ المشتريات',
  'Low stock': 'مخزون منخفض',
  'Out of stock': 'نفد المخزون',
  'Type': 'النوع',
  'Apply adjustment': 'تطبيق التعديل',
  'Today': 'اليوم',
  'Yesterday': 'أمس',
  'This week': 'هذا الأسبوع',
  'This month': 'هذا الشهر',
  'Close': 'إغلاق',
  'Print': 'طباعة',
  'Scan': 'مسح',
  'Scan barcode or search product (Name, SKU, Barcode)':
      'امسح الباركود أو ابحث عن منتج (الاسم، الرمز، الباركود)',
  'Add to order': 'إضافة إلى الطلب',
  'in stock': 'في المخزون',
  'View sale': 'عرض البيع',
  'Reprint (available in F7)': 'إعادة الطباعة (F7)',
  'Return (available in F5)': 'مرتجع (F5)',
  'Add Note': 'إضافة ملاحظة',
  'Hold Sale': 'تعليق البيع',
  'Clear Cart': 'مسح السلة',
  'Unit price': 'سعر الوحدة',
  'Edit unit price': 'تعديل سعر الوحدة',
  'Edit price': 'تعديل السعر',
  'Edit price (F6 for latest item)': 'تعديل السعر (F6 لآخر منتج)',
  'Use default price': 'استخدام السعر الافتراضي',
  'Amount': 'المبلغ',
  'Rate': 'النسبة',
  'Add gross discount': 'إضافة خصم إجمالي',
  'Order note': 'ملاحظة الطلب',
  'Add a note for this sale...': 'أضف ملاحظة لهذا البيع...',
  'Save note': 'حفظ الملاحظة',
  'Search name, phone or email': 'ابحث بالاسم أو الهاتف أو البريد',
  'Sync now': 'مزامنة الآن',
  'Start a sale': 'بدء عملية بيع',
  'Start new sale': 'بدء عملية بيع جديدة',
  'View sales history': 'عرض سجل المبيعات',
  'Share': 'مشاركة',
  'Email or username': 'البريد الإلكتروني أو اسم المستخدم',
  'Password': 'كلمة المرور',
  'Remember me': 'تذكرني',
  'Forgot password?': 'هل نسيت كلمة المرور؟',
  'Sign in': 'تسجيل الدخول',
  'English': 'English',
  'Arabic': 'العربية',
  'Language': 'اللغة',
  'Basmati Rice 5kg': 'أرز بسمتي 5 كجم',
  'Whole Wheat Flour': 'دقيق القمح الكامل',
  'Toor Dal 1kg': 'عدس تور 1 كجم',
  'Organic Sugar': 'سكر عضوي',
  'Sunflower Oil 1L': 'زيت دوار الشمس 1 لتر',
  'Tata Salt': 'ملح تاتا',
  'Fresh Milk 1L': 'حليب طازج 1 لتر',
  'Orange Juice': 'عصير برتقال',
  'Mineral Water': 'مياه معدنية',
  'Cola 750ml': 'كولا 750 مل',
  'Green Tea': 'شاي أخضر',
  'Instant Coffee': 'قهوة سريعة التحضير',
  'Masala Chips': 'رقائق ماسالا',
  'Salted Peanuts': 'فول سوداني مملح',
  'Cream Biscuits': 'بسكويت بالكريمة',
  'Dark Chocolate': 'شوكولاتة داكنة',
  'Roasted Makhana': 'مخانا محمصة',
  'Granola Bar': 'لوح جرانولا',
  'Dishwash Liquid': 'سائل غسيل الصحون',
  'Laundry Detergent': 'منظف الغسيل',
  'Floor Cleaner': 'منظف الأرضيات',
  'Kitchen Towels': 'مناشف المطبخ',
  'Garbage Bags': 'أكياس القمامة',
  'Aluminium Foil': 'رقائق ألمنيوم',
  'Herbal Shampoo': 'شامبو عشبي',
  'Bath Soap': 'صابون استحمام',
  'Toothpaste': 'معجون أسنان',
  'Hand Wash': 'غسول اليدين',
  'Face Cream': 'كريم للوجه',
  'Body Lotion': 'لوشن للجسم',
  'Store open': 'المتجر مفتوح',
  'Good morning, Nishad': 'صباح الخير، نيشاد',
  'Your store is on track. Here’s today at a glance.':
      'متجرك يسير بشكل جيد. إليك ملخص اليوم.',
  'Add stock': 'إضافة مخزون',
  "Today's sales": 'مبيعات اليوم',
  'Transactions': 'المعاملات',
  'Gross profit': 'إجمالي الربح',
  'Pending sync': 'مزامنة معلقة',
  'Purchases today': 'مشتريات اليوم',
  '7-day sales summary': 'ملخص مبيعات 7 أيام',
  'Recent sales': 'أحدث المبيعات',
  'Manage pricing, stock and barcodes.': 'إدارة الأسعار والمخزون والباركود.',
  'Organize products for faster checkout.': 'نظّم المنتجات لإتمام البيع بسرعة.',
  'Receive supplier stock locally.': 'استلام مخزون المورد محلياً.',
  'Live local stock and adjustments.': 'المخزون المحلي والتعديلات المباشرة.',
  'Customer profiles for faster billing.': 'ملفات العملاء لفوترة أسرع.',
  'Sales history': 'سجل المبيعات',
  'Local and synchronized transactions.': 'المعاملات المحلية والمتزامنة.',
  'Sales report': 'تقرير المبيعات',
  'Performance from locally available transactions.':
      'الأداء استناداً إلى المعاملات المحلية.',
  'Total sales': 'إجمالي المبيعات',
  'Total orders': 'إجمالي الطلبات',
  'Average order': 'متوسط الطلب',
  'Tax collected': 'الضريبة المحصلة',
  'Sales trend': 'اتجاه المبيعات',
  'Top selling products': 'المنتجات الأكثر مبيعاً',
  'Synchronization': 'المزامنة',
  'Offline changes remain safely queued on this device.':
      'تظل التغييرات دون اتصال محفوظة بأمان على هذا الجهاز.',
  'Internet status': 'حالة الإنترنت',
  'Pending records': 'السجلات المعلقة',
  'Failed records': 'السجلات الفاشلة',
  'Sync queue': 'قائمة انتظار المزامنة',
  'All local records are synchronized': 'تمت مزامنة جميع السجلات المحلية',
  'Pending': 'معلق',
  'Total': 'الإجمالي',
  'Tax': 'الضريبة',
  'Configure your business and connected services.':
      'إعداد نشاطك التجاري والخدمات المتصلة.',
  'Business profile': 'ملف النشاط التجاري',
  'Tax settings': 'إعدادات الضريبة',
  'Invoice settings': 'إعدادات الفاتورة',
  'Printer settings': 'إعدادات الطابعة',
  'Sync settings': 'إعدادات المزامنة',
  'Appearance': 'المظهر',
  'User & profile': 'المستخدم والملف الشخصي',
  'Light theme': 'المظهر الفاتح',
  'Receipt template and numbering': 'قالب الإيصال والترقيم',
  'Sell smarter.\nStay in control.': 'بِع بذكاء.\nابقَ مسيطراً.',
  'Fast checkout, accurate stock, and an offline-first workflow for modern retail.':
      'دفع سريع، ومخزون دقيق، وتجربة تعمل دون اتصال لتجارة التجزئة الحديثة.',
  'Ready even when the internet is not': 'جاهز حتى عندما لا يتوفر الإنترنت',
  'Welcome back': 'مرحباً بعودتك',
  'Sign in to open your store.': 'سجّل الدخول لفتح متجرك.',
  'Smart POS for your business': 'نظام نقاط بيع ذكي لأعمالك',
  'Run every sale\nwith confidence.': 'أدِر كل عملية بيع\nبثقة.',
  'Check out customers faster, keep stock accurate, and continue selling even when the connection drops.':
      'أنهِ معاملات العملاء بسرعة، وحافظ على دقة المخزون، واستمر في البيع حتى عند انقطاع الاتصال.',
  'Fast checkout': 'دفع سريع',
  'Accurate stock': 'مخزون دقيق',
  'Offline ready': 'جاهز دون اتصال',
  'Offline sales are saved and synced when you reconnect.':
      'تُحفظ المبيعات دون اتصال وتتم مزامنتها عند عودة الإنترنت.',
  'Start your shift': 'ابدأ ورديتك',
  'Sign in to access your register, products, and sales for this location.':
      'سجّل الدخول للوصول إلى الصندوق والمنتجات والمبيعات في هذا الموقع.',
  'Remember this account': 'تذكّر هذا الحساب',
  'Continue to Eazy POS': 'المتابعة إلى إيزي بوس',
  'Secure access for your business and saved staff profiles.':
      'وصول آمن لنشاطك التجاري وملفات الموظفين المحفوظة.',
  'Sale complete': 'اكتملت عملية البيع',
  'New sale ready': 'عملية بيع جديدة جاهزة',
  'Thank you for shopping with us': 'شكراً لتسوقك معنا',
  'Pending synchronization': 'في انتظار المزامنة',
  'Adjust': 'تعديل',
  'No products match this filter': 'لا توجد منتجات مطابقة لهذا الفلتر',
  'Tap a product to start a sale': 'اضغط على منتج لبدء عملية بيع',
  'Minimum': 'الحد الأدنى',
  'left': 'متبقي',
  'Out': 'نفد',
  'UPI / Digital': 'دفع إلكتروني',
  'Collect': 'تحصيل',
  'Enter your username and password.': 'أدخل اسم المستخدم وكلمة المرور.',
  'The username or password is incorrect.':
      'اسم المستخدم أو كلمة المرور غير صحيحة.',
  'Login is not configured. Add the OAuth client secret to the build.':
      'تسجيل الدخول غير مُعد. أضف سر عميل OAuth إلى عملية البناء.',
  'Unable to reach the server. Check your connection.':
      'تعذر الوصول إلى الخادم. تحقق من اتصالك.',
  'Login failed. Please try again.': 'فشل تسجيل الدخول. حاول مرة أخرى.',
};
